/* ============================================================================
   AI STACK CATALOG  —  this is your data + referral layer.
   ----------------------------------------------------------------------------
   This is the ONE file you'll edit most. To add a tool, copy a block below,
   paste it, and change the fields. To monetize, replace each "url" with YOUR
   affiliate / referral tracking link from the program named in "affiliate".

   FIELD GUIDE
     id          : unique short slug (no spaces)
     name        : display name
     category    : short human label shown on the card
     tags        : which USE-CASE domains this tool serves. MUST match the
                   domain ids in scoring.js (sales, marketing, support,
                   knowledge, docs, automation, data, hr, finance, itdev,
                   meetings). A tool can serve several.
     desc        : one-line "what it does"
     sizes       : company sizes it fits: 'small' (1-50), 'mid' (51-500),
                   'large' (500+)
     priceTier   : 'free' | 'low' | 'mid' | 'high'  (used for budget matching)
     hasFreePlan : true if there's a free plan (not just a trial)
     price       : human-readable starting price
     ease        : setup difficulty 1 (no-code/instant) .. 3 (needs tech help)
     affiliate   : the referral/affiliate program & network (or "None")
     commission  : rough payout — ALWAYS verify the live rate when you sign up
     url         : the link the "Try it" button uses  ->  PUT YOUR AFFILIATE
                   LINK HERE. For now it points at the vendor's site.
     site        : vendor homepage (reference)
   ========================================================================== */

const AI_TOOLS = [
  // ---- General assistants (cross-functional) ----
  { id:"chatgpt", name:"ChatGPT", category:"General AI assistant",
    tags:["marketing","docs","data","knowledge"],
    desc:"Versatile assistant for writing, analysis, brainstorming, and coding.",
    sizes:["small","mid","large"], priceTier:"low", hasFreePlan:true, price:"Free; Plus $20/mo",
    ease:1, affiliate:"None (no public affiliate program)", commission:"—",
    url:"https://chatgpt.com", site:"https://chatgpt.com" },

  { id:"claude", name:"Claude", category:"General AI assistant",
    tags:["docs","knowledge","data","marketing"],
    desc:"AI assistant strong at long-form writing, analysis, and careful reasoning.",
    sizes:["small","mid","large"], priceTier:"low", hasFreePlan:true, price:"Free; Pro $20/mo",
    ease:1, affiliate:"None (no public affiliate program)", commission:"—",
    url:"https://claude.ai", site:"https://claude.ai" },

  // ---- Marketing & content ----
  { id:"jasper", name:"Jasper", category:"Marketing copywriter",
    tags:["marketing"],
    desc:"Marketing-focused AI writer for on-brand campaigns, blogs, and ads.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:false, price:"7-day trial; $39/mo",
    ease:1, affiliate:"PartnerStack", commission:"25–30% recurring (1 yr)",
    url:"https://www.jasper.ai", site:"https://www.jasper.ai" },

  { id:"copyai", name:"Copy.ai", category:"Copywriting + GTM",
    tags:["marketing","sales"],
    desc:"AI copywriter and go-to-market workflows for marketing and sales teams.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:true, price:"Free; Pro $49/mo",
    ease:1, affiliate:"PartnerStack / Impact", commission:"~20–45% recurring",
    url:"https://www.copy.ai", site:"https://www.copy.ai" },

  { id:"writesonic", name:"Writesonic", category:"AI writer + SEO",
    tags:["marketing"],
    desc:"AI article writer with built-in SEO optimization.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:true, price:"Free trial; $39/mo",
    ease:1, affiliate:"In-house", commission:"30% recurring (lifetime)",
    url:"https://writesonic.com", site:"https://writesonic.com" },

  { id:"surfer", name:"Surfer SEO", category:"SEO content optimization",
    tags:["marketing"],
    desc:"Optimize and generate content to rank on Google and AI search.",
    sizes:["small","mid"], priceTier:"high", hasFreePlan:false, price:"$99/mo",
    ease:2, affiliate:"PartnerStack", commission:"CPA: 15% first yr / 75% first mo",
    url:"https://surferseo.com", site:"https://surferseo.com" },

  { id:"frase", name:"Frase", category:"SEO research + writing",
    tags:["marketing"],
    desc:"AI SEO research, content briefs, and writing in one place.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:false, price:"Trial; $15/mo",
    ease:2, affiliate:"In-house", commission:"~30% recurring",
    url:"https://www.frase.io", site:"https://www.frase.io" },

  { id:"grammarly", name:"Grammarly", category:"Writing assistant",
    tags:["marketing","docs"],
    desc:"AI assistant for grammar, tone, and clarity everywhere you type.",
    sizes:["small","mid","large"], priceTier:"low", hasFreePlan:true, price:"Free; Pro $12/mo",
    ease:1, affiliate:"CJ / Impact", commission:"Bounty per signup / sale",
    url:"https://www.grammarly.com", site:"https://www.grammarly.com" },

  { id:"canva", name:"Canva", category:"Design + AI Magic Studio",
    tags:["marketing"],
    desc:"Design platform with AI for graphics, social posts, and decks.",
    sizes:["small","mid","large"], priceTier:"low", hasFreePlan:true, price:"Free; Pro $15/mo",
    ease:1, affiliate:"Canva Affiliate (Impact)", commission:"Up to ~20%",
    url:"https://www.canva.com", site:"https://www.canva.com" },

  { id:"firefly", name:"Adobe Firefly", category:"AI image generation",
    tags:["marketing"],
    desc:"Commercially-safe AI image generation integrated with Adobe apps.",
    sizes:["small","mid","large"], priceTier:"low", hasFreePlan:true, price:"Free; from $10/mo",
    ease:1, affiliate:"Adobe Affiliate Program", commission:"Varies by plan",
    url:"https://www.adobe.com/products/firefly.html", site:"https://www.adobe.com/products/firefly.html" },

  { id:"midjourney", name:"Midjourney", category:"AI image generation",
    tags:["marketing"],
    desc:"High-end AI image generation for striking, stylized visuals.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:false, price:"$10/mo",
    ease:2, affiliate:"None", commission:"—",
    url:"https://www.midjourney.com", site:"https://www.midjourney.com" },

  { id:"synthesia", name:"Synthesia", category:"AI avatar video",
    tags:["marketing","hr"],
    desc:"Turn scripts into AI-avatar videos — great for training and explainers.",
    sizes:["small","mid","large"], priceTier:"mid", hasFreePlan:false, price:"Demo; $18/mo",
    ease:1, affiliate:"In-house", commission:"20–25% recurring",
    url:"https://www.synthesia.io", site:"https://www.synthesia.io" },

  { id:"heygen", name:"HeyGen", category:"AI avatar video",
    tags:["marketing"],
    desc:"AI avatar and video generation with realistic voices and translation.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:true, price:"Free; $24/mo",
    ease:1, affiliate:"In-house", commission:"Recurring (verify rate)",
    url:"https://www.heygen.com", site:"https://www.heygen.com" },

  { id:"descript", name:"Descript", category:"Video & podcast editing",
    tags:["marketing"],
    desc:"Edit video & audio by editing text; AI for filler-word removal and more.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:true, price:"Free; $24/mo",
    ease:2, affiliate:"In-house", commission:"Recurring (lower rate)",
    url:"https://www.descript.com", site:"https://www.descript.com" },

  { id:"pictory", name:"Pictory", category:"Text-to-video",
    tags:["marketing"],
    desc:"Turn blog posts and scripts into short videos automatically.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:false, price:"Trial; $25/mo",
    ease:1, affiliate:"In-house", commission:"30% recurring",
    url:"https://pictory.ai", site:"https://pictory.ai" },

  { id:"elevenlabs", name:"ElevenLabs", category:"AI voice / TTS",
    tags:["marketing"],
    desc:"Realistic AI voiceovers and text-to-speech in many languages.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; from $5/mo",
    ease:1, affiliate:"In-house", commission:"22% recurring (1 yr)",
    url:"https://elevenlabs.io", site:"https://elevenlabs.io" },

  { id:"murf", name:"Murf", category:"AI voice generator",
    tags:["marketing","hr"],
    desc:"AI voiceovers for presentations, e-learning, and product videos.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; $19/mo",
    ease:1, affiliate:"In-house", commission:"15% recurring (24 mo)",
    url:"https://murf.ai", site:"https://murf.ai" },

  { id:"gamma", name:"Gamma", category:"AI presentations",
    tags:["marketing","docs"],
    desc:"Generate polished presentations, docs, and webpages from a prompt.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; $10/mo",
    ease:1, affiliate:"In-house referral", commission:"Credit / referral",
    url:"https://gamma.app", site:"https://gamma.app" },

  { id:"durable", name:"Durable", category:"AI website builder",
    tags:["marketing"],
    desc:"Build a small-business website in seconds with AI.",
    sizes:["small"], priceTier:"low", hasFreePlan:false, price:"Trial; $12/mo",
    ease:1, affiliate:"In-house", commission:"Recurring (verify rate)",
    url:"https://durable.co", site:"https://durable.co" },

  { id:"getresponse", name:"GetResponse", category:"Email marketing + AI",
    tags:["marketing","automation"],
    desc:"Email marketing & automation with AI campaign and content tools.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; $19/mo",
    ease:1, affiliate:"In-house", commission:"33% recurring or $100 bounty",
    url:"https://www.getresponse.com", site:"https://www.getresponse.com" },

  // ---- Sales & revenue ----
  { id:"close", name:"Close CRM", category:"CRM for SMB sales",
    tags:["sales"],
    desc:"CRM with AI to help small sales teams call, email, and close faster.",
    sizes:["small","mid"], priceTier:"high", hasFreePlan:false, price:"Trial; $49/seat",
    ease:2, affiliate:"PartnerStack", commission:"Recurring (verify rate)",
    url:"https://www.close.com", site:"https://www.close.com" },

  { id:"apollo", name:"Apollo.io", category:"Prospecting + outreach",
    tags:["sales"],
    desc:"B2B contact database with AI for finding and emailing leads.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:true, price:"Free; $49/mo",
    ease:2, affiliate:"In-house / partner", commission:"Recurring (verify rate)",
    url:"https://www.apollo.io", site:"https://www.apollo.io" },

  // ---- Meetings & productivity ----
  { id:"otter", name:"Otter.ai", category:"Meeting transcription",
    tags:["meetings"],
    desc:"Live meeting transcription, notes, and summaries.",
    sizes:["small","mid","large"], priceTier:"low", hasFreePlan:true, price:"Free; $17/mo",
    ease:1, affiliate:"In-house", commission:"Recurring (verify rate)",
    url:"https://otter.ai", site:"https://otter.ai" },

  { id:"fireflies", name:"Fireflies.ai", category:"AI meeting notetaker",
    tags:["meetings","sales"],
    desc:"Records, transcribes, and summarizes meetings; pushes notes to your CRM.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; $10/mo",
    ease:1, affiliate:"In-house", commission:"Recurring (verify rate)",
    url:"https://fireflies.ai", site:"https://fireflies.ai" },

  { id:"fathom", name:"Fathom", category:"AI meeting notetaker",
    tags:["meetings","sales"],
    desc:"Free AI meeting notetaker and summarizer popular with sales teams.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; Pro from $19/mo",
    ease:1, affiliate:"Limited — verify availability", commission:"Verify",
    url:"https://fathom.video", site:"https://fathom.video" },

  { id:"motion", name:"Motion", category:"AI calendar & PM",
    tags:["meetings"],
    desc:"AI calendar and project manager that auto-plans your day.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:false, price:"Trial; $19/mo",
    ease:1, affiliate:"In-house", commission:"~30% (verify rate)",
    url:"https://www.usemotion.com", site:"https://www.usemotion.com" },

  // ---- Customer support ----
  { id:"tidio", name:"Tidio", category:"AI chatbot + live chat",
    tags:["support"],
    desc:"AI chatbots and live chat to handle customer questions on your site.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; $29/mo",
    ease:1, affiliate:"PartnerStack", commission:"Recurring (verify rate)",
    url:"https://www.tidio.com", site:"https://www.tidio.com" },

  { id:"chatbase", name:"Chatbase", category:"Custom AI chatbot",
    tags:["support","knowledge"],
    desc:"Build a custom AI chatbot trained on your docs and website.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; $19/mo",
    ease:2, affiliate:"In-house", commission:"Recurring (verify rate)",
    url:"https://www.chatbase.co", site:"https://www.chatbase.co" },

  { id:"intercomfin", name:"Intercom Fin", category:"AI support agent",
    tags:["support"],
    desc:"AI customer-service agent that resolves tickets automatically.",
    sizes:["mid","large"], priceTier:"high", hasFreePlan:false, price:"From $29/seat + usage",
    ease:2, affiliate:"Partner program", commission:"Channel/partner (verify)",
    url:"https://www.intercom.com/fin", site:"https://www.intercom.com/fin" },

  // ---- Knowledge management ----
  { id:"notion", name:"Notion AI", category:"Workspace + knowledge",
    tags:["knowledge","docs"],
    desc:"AI inside your workspace for notes, docs, and team knowledge.",
    sizes:["small","mid","large"], priceTier:"low", hasFreePlan:true, price:"Free; AI from $10/mo",
    ease:1, affiliate:"Notion Partner Program", commission:"Up to ~50%",
    url:"https://www.notion.so/product/ai", site:"https://www.notion.so/product/ai" },

  { id:"glean", name:"Glean", category:"Enterprise AI search",
    tags:["knowledge"],
    desc:"Enterprise search + AI assistant across all your company's apps.",
    sizes:["mid","large"], priceTier:"high", hasFreePlan:false, price:"Custom (enterprise)",
    ease:3, affiliate:"Partner / referral (enterprise)", commission:"Channel deal (verify)",
    url:"https://www.glean.com", site:"https://www.glean.com" },

  // ---- Document & RFP automation ----
  { id:"loopio", name:"Loopio", category:"RFP & proposal automation",
    tags:["docs","sales"],
    desc:"AI-assisted RFP, security questionnaire, and proposal responses.",
    sizes:["mid","large"], priceTier:"high", hasFreePlan:false, price:"Custom (enterprise)",
    ease:2, affiliate:"Partner / referral", commission:"Channel deal (verify)",
    url:"https://loopio.com", site:"https://loopio.com" },

  // ---- Automation ----
  { id:"zapier", name:"Zapier", category:"Workflow automation",
    tags:["automation"],
    desc:"Connect 7,000+ apps and automate workflows, now with AI steps.",
    sizes:["small","mid","large"], priceTier:"low", hasFreePlan:true, price:"Free; from $20/mo",
    ease:2, affiliate:"Impact", commission:"Recurring (verify rate)",
    url:"https://zapier.com", site:"https://zapier.com" },

  { id:"make", name:"Make", category:"Visual automation",
    tags:["automation"],
    desc:"Visual builder for complex, multi-step automations and AI agents.",
    sizes:["small","mid","large"], priceTier:"low", hasFreePlan:true, price:"Free; from $9/mo",
    ease:2, affiliate:"Partner program", commission:"Recurring (verify rate)",
    url:"https://www.make.com", site:"https://www.make.com" },

  // ---- Data & analytics ----
  { id:"julius", name:"Julius AI", category:"AI data analyst",
    tags:["data","finance"],
    desc:"Chat with your spreadsheets and databases to analyze and visualize data.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; $20/mo",
    ease:1, affiliate:"In-house", commission:"Recurring (verify rate)",
    url:"https://julius.ai", site:"https://julius.ai" },

  // ---- Finance & back office ----
  { id:"ramp", name:"Ramp", category:"AI finance & spend",
    tags:["finance"],
    desc:"Corporate cards, expense, and AP automation with AI controls.",
    sizes:["small","mid","large"], priceTier:"free", hasFreePlan:true, price:"Free (card-based)",
    ease:2, affiliate:"Referral / partner", commission:"Bounty per signup (verify)",
    url:"https://ramp.com", site:"https://ramp.com" },

  // ---- IT & software development ----
  { id:"copilot", name:"GitHub Copilot", category:"AI pair programmer",
    tags:["itdev"],
    desc:"AI code completion and chat inside your editor.",
    sizes:["small","mid","large"], priceTier:"low", hasFreePlan:true, price:"Free tier; $10/mo",
    ease:2, affiliate:"None", commission:"—",
    url:"https://github.com/features/copilot", site:"https://github.com/features/copilot" },

  { id:"cursor", name:"Cursor", category:"AI code editor",
    tags:["itdev"],
    desc:"AI-first code editor that writes and edits code from natural language.",
    sizes:["small","mid","large"], priceTier:"low", hasFreePlan:true, price:"Free; Pro $20/mo",
    ease:2, affiliate:"None", commission:"—",
    url:"https://www.cursor.com", site:"https://www.cursor.com" },

  /* ===================== EXPANDED CATALOG ===================== */

  // ---- General assistants & search ----
  { id:"gemini", name:"Gemini", category:"General AI assistant",
    tags:["marketing","docs","data","knowledge"],
    desc:"Google's multimodal AI assistant, strong on research and Workspace integration.",
    sizes:["small","mid","large"], priceTier:"low", hasFreePlan:true, price:"Free; from $20/mo",
    ease:1, affiliate:"None", commission:"—",
    url:"https://gemini.google.com", site:"https://gemini.google.com" },
  { id:"mscopilot", name:"Microsoft 365 Copilot", category:"Productivity assistant",
    tags:["docs","knowledge","data"],
    desc:"AI across Word, Excel, Outlook, and Teams for everyday office work.",
    sizes:["mid","large"], priceTier:"mid", hasFreePlan:false, price:"$30/user/mo",
    ease:2, affiliate:"None", commission:"—",
    url:"https://www.microsoft.com/microsoft-365/copilot", site:"https://www.microsoft.com/microsoft-365/copilot" },
  { id:"perplexity", name:"Perplexity", category:"AI answer engine",
    tags:["knowledge","data","marketing"],
    desc:"AI search that answers questions with cited sources.",
    sizes:["small","mid","large"], priceTier:"low", hasFreePlan:true, price:"Free; Pro $20/mo",
    ease:1, affiliate:"Verify availability", commission:"Verify",
    url:"https://www.perplexity.ai", site:"https://www.perplexity.ai" },

  // ---- Marketing & content ----
  { id:"hubspot", name:"HubSpot", category:"CRM + marketing suite",
    tags:["marketing","sales","automation"],
    desc:"All-in-one CRM, marketing, and sales platform with AI throughout.",
    sizes:["small","mid","large"], priceTier:"mid", hasFreePlan:true, price:"Free; paid scales up",
    ease:2, affiliate:"Impact", commission:"Up to 30% recurring (verify)",
    url:"https://www.hubspot.com", site:"https://www.hubspot.com" },
  { id:"mailchimp", name:"Mailchimp", category:"Email marketing + AI",
    tags:["marketing","automation"],
    desc:"Email marketing with AI content and send-time optimization.",
    sizes:["small","mid","large"], priceTier:"low", hasFreePlan:true, price:"Free; from $13/mo",
    ease:1, affiliate:"Has affiliate program (verify)", commission:"Verify",
    url:"https://www.mailchimp.com", site:"https://www.mailchimp.com" },
  { id:"semrush", name:"Semrush", category:"SEO & marketing suite",
    tags:["marketing"],
    desc:"SEO, content, and competitor research with AI writing tools.",
    sizes:["small","mid"], priceTier:"high", hasFreePlan:false, price:"Trial; $139/mo",
    ease:2, affiliate:"Impact (Semrush Affiliate)", commission:"Up to $200 CPA (verify)",
    url:"https://www.semrush.com", site:"https://www.semrush.com" },
  { id:"buffer", name:"Buffer", category:"Social media scheduling",
    tags:["marketing"],
    desc:"Schedule social posts with an AI assistant for ideas and captions.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; from $6/mo",
    ease:1, affiliate:"Has affiliate program (verify)", commission:"Verify",
    url:"https://buffer.com", site:"https://buffer.com" },
  { id:"adcreative", name:"AdCreative.ai", category:"AI ad creative",
    tags:["marketing"],
    desc:"Generate conversion-focused ad creatives and copy in seconds.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:false, price:"7-day trial; $39/mo",
    ease:1, affiliate:"In-house", commission:"~30% recurring (verify)",
    url:"https://www.adcreative.ai", site:"https://www.adcreative.ai" },
  { id:"opusclip", name:"Opus Clip", category:"AI video clipping",
    tags:["marketing"],
    desc:"Turn long videos into viral short clips automatically.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; from $15/mo",
    ease:1, affiliate:"In-house (verify)", commission:"Verify",
    url:"https://www.opus.pro", site:"https://www.opus.pro" },
  { id:"runway", name:"Runway", category:"AI video generation",
    tags:["marketing"],
    desc:"Generative AI video and editing for creative teams.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; from $15/mo",
    ease:2, affiliate:"Verify availability", commission:"Verify",
    url:"https://runwayml.com", site:"https://runwayml.com" },
  { id:"leonardo", name:"Leonardo.ai", category:"AI image generation",
    tags:["marketing"],
    desc:"AI image and asset generation with fine creative control.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; from $12/mo",
    ease:1, affiliate:"Verify availability", commission:"Verify",
    url:"https://leonardo.ai", site:"https://leonardo.ai" },
  { id:"beautifulai", name:"Beautiful.ai", category:"AI presentations",
    tags:["marketing","docs"],
    desc:"Presentation software that designs slides for you as you type.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:false, price:"Trial; $12/mo",
    ease:1, affiliate:"Has affiliate program (verify)", commission:"Verify",
    url:"https://www.beautiful.ai", site:"https://www.beautiful.ai" },

  // ---- Sales & revenue ----
  { id:"clay", name:"Clay", category:"AI prospecting & enrichment",
    tags:["sales"],
    desc:"Build lead lists and run AI research/outreach at scale.",
    sizes:["small","mid"], priceTier:"high", hasFreePlan:true, price:"Free; from $149/mo",
    ease:3, affiliate:"Has affiliate program (verify)", commission:"Verify",
    url:"https://www.clay.com", site:"https://www.clay.com" },
  { id:"instantly", name:"Instantly.ai", category:"Cold email outreach",
    tags:["sales"],
    desc:"Send and scale cold email campaigns with AI deliverability tools.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:false, price:"From $37/mo",
    ease:2, affiliate:"In-house", commission:"~30% recurring (verify)",
    url:"https://instantly.ai", site:"https://instantly.ai" },
  { id:"lemlist", name:"lemlist", category:"Outreach & sequences",
    tags:["sales"],
    desc:"Multichannel sales outreach with AI personalization.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:false, price:"From $39/mo",
    ease:2, affiliate:"Has affiliate program (verify)", commission:"Verify",
    url:"https://www.lemlist.com", site:"https://www.lemlist.com" },
  { id:"regie", name:"Regie.ai", category:"AI sales agents",
    tags:["sales","docs"],
    desc:"AI sales agents that research, draft, and send personalized outbound at scale.",
    sizes:["mid","large"], priceTier:"high", hasFreePlan:false, price:"From $59/seat",
    ease:2, affiliate:"Verify availability", commission:"Verify",
    url:"https://www.regie.ai", site:"https://www.regie.ai" },
  { id:"lavender", name:"Lavender", category:"AI email coach",
    tags:["sales"],
    desc:"Real-time AI coaching to write better sales emails.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:true, price:"Free; from $29/mo",
    ease:1, affiliate:"Verify availability", commission:"Verify",
    url:"https://www.lavender.ai", site:"https://www.lavender.ai" },

  // ---- Customer support ----
  { id:"zendeskai", name:"Zendesk AI", category:"AI customer service",
    tags:["support"],
    desc:"AI agents and assist features inside the Zendesk help desk.",
    sizes:["mid","large"], priceTier:"high", hasFreePlan:false, price:"Paid (per agent + AI add-on)",
    ease:2, affiliate:"Partner program (verify)", commission:"Verify",
    url:"https://www.zendesk.com/service/ai", site:"https://www.zendesk.com/service/ai" },
  { id:"freshchat", name:"Freshchat (Freddy AI)", category:"AI chat & support",
    tags:["support"],
    desc:"AI-powered chat and ticketing for customer support teams.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:true, price:"Free; paid scales",
    ease:2, affiliate:"Verify availability", commission:"Verify",
    url:"https://www.freshworks.com/live-chat-software", site:"https://www.freshworks.com/live-chat-software" },
  { id:"ada", name:"Ada", category:"AI support automation",
    tags:["support"],
    desc:"Enterprise AI agent that automates customer service conversations.",
    sizes:["mid","large"], priceTier:"high", hasFreePlan:false, price:"Custom (enterprise)",
    ease:3, affiliate:"Partner / referral (verify)", commission:"Verify",
    url:"https://www.ada.cx", site:"https://www.ada.cx" },

  // ---- Knowledge management ----
  { id:"guru", name:"Guru", category:"AI knowledge base",
    tags:["knowledge"],
    desc:"Company wiki and enterprise search with AI-generated answers.",
    sizes:["small","mid","large"], priceTier:"low", hasFreePlan:true, price:"Free; from $15/user",
    ease:2, affiliate:"Verify availability", commission:"Verify",
    url:"https://www.getguru.com", site:"https://www.getguru.com" },
  { id:"mem", name:"Mem", category:"AI notes & knowledge",
    tags:["knowledge"],
    desc:"Self-organizing AI notes app that surfaces what you need.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; from $10/mo",
    ease:1, affiliate:"Verify availability", commission:"Verify",
    url:"https://get.mem.ai", site:"https://get.mem.ai" },

  // ---- Document, proposals & legal ----
  { id:"pandadoc", name:"PandaDoc", category:"Docs & proposals",
    tags:["docs","sales"],
    desc:"Create, send, and e-sign proposals and contracts with AI drafting.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; from $19/mo",
    ease:1, affiliate:"PartnerStack / Impact (verify)", commission:"Verify",
    url:"https://www.pandadoc.com", site:"https://www.pandadoc.com" },
  { id:"harvey", name:"Harvey", category:"AI for legal",
    tags:["docs","finance"],
    desc:"Domain-specific AI for legal and professional services work.",
    sizes:["large"], priceTier:"high", hasFreePlan:false, price:"Custom (enterprise)",
    ease:3, affiliate:"None (enterprise)", commission:"—",
    url:"https://www.harvey.ai", site:"https://www.harvey.ai" },
  { id:"spellbook", name:"Spellbook", category:"AI contract review",
    tags:["docs"],
    desc:"AI that drafts and reviews contracts inside Microsoft Word.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:false, price:"Paid (per seat)",
    ease:2, affiliate:"Verify availability", commission:"Verify",
    url:"https://www.spellbook.legal", site:"https://www.spellbook.legal" },

  // ---- Automation & agents ----
  { id:"n8n", name:"n8n", category:"Workflow automation",
    tags:["automation"],
    desc:"Open-source, self-hostable automation with AI agent nodes.",
    sizes:["small","mid","large"], priceTier:"low", hasFreePlan:true, price:"Free (self-host); from $20/mo",
    ease:3, affiliate:"Verify availability", commission:"Verify",
    url:"https://n8n.io", site:"https://n8n.io" },
  { id:"lindy", name:"Lindy", category:"AI agents",
    tags:["automation"],
    desc:"Build AI assistants that handle email, meetings, and workflows.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:true, price:"Free; from $30/mo",
    ease:2, affiliate:"Verify availability", commission:"Verify",
    url:"https://www.lindy.ai", site:"https://www.lindy.ai" },
  { id:"bardeen", name:"Bardeen", category:"Browser automation",
    tags:["automation"],
    desc:"Automate repetitive browser and SaaS tasks with AI.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; from $10/mo",
    ease:2, affiliate:"Verify availability", commission:"Verify",
    url:"https://www.bardeen.ai", site:"https://www.bardeen.ai" },
  { id:"gumloop", name:"Gumloop", category:"No-code AI automation",
    tags:["automation","data"],
    desc:"Drag-and-drop builder for AI-powered automations.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:true, price:"Free; paid scales",
    ease:2, affiliate:"Verify availability", commission:"Verify",
    url:"https://www.gumloop.com", site:"https://www.gumloop.com" },

  // ---- Data & analytics ----
  { id:"hex", name:"Hex", category:"AI data workspace",
    tags:["data"],
    desc:"Notebook-style analytics with an AI assistant for SQL and Python.",
    sizes:["mid","large"], priceTier:"mid", hasFreePlan:true, price:"Free; paid scales",
    ease:3, affiliate:"Verify availability", commission:"Verify",
    url:"https://hex.tech", site:"https://hex.tech" },
  { id:"powerbi", name:"Power BI Copilot", category:"BI & dashboards",
    tags:["data"],
    desc:"Microsoft's BI platform with AI for reports and insights.",
    sizes:["mid","large"], priceTier:"low", hasFreePlan:false, price:"From $10/user/mo",
    ease:2, affiliate:"None", commission:"—",
    url:"https://www.microsoft.com/power-bi", site:"https://www.microsoft.com/power-bi" },
  { id:"akkio", name:"Akkio", category:"No-code predictive AI",
    tags:["data"],
    desc:"Predictive analytics and AI on your data without a data team.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:false, price:"From $49/mo",
    ease:2, affiliate:"Verify availability", commission:"Verify",
    url:"https://www.akkio.com", site:"https://www.akkio.com" },

  // ---- HR, training & recruiting ----
  { id:"paradox", name:"Paradox (Olivia)", category:"AI recruiting assistant",
    tags:["hr"],
    desc:"Conversational AI that screens and schedules candidates.",
    sizes:["mid","large"], priceTier:"high", hasFreePlan:false, price:"Custom (enterprise)",
    ease:2, affiliate:"Partner program (verify)", commission:"Verify",
    url:"https://www.paradox.ai", site:"https://www.paradox.ai" },
  { id:"textio", name:"Textio", category:"Inclusive writing AI",
    tags:["hr","marketing"],
    desc:"AI guidance for job posts and performance feedback.",
    sizes:["mid","large"], priceTier:"high", hasFreePlan:false, price:"Custom",
    ease:2, affiliate:"None", commission:"—",
    url:"https://textio.com", site:"https://textio.com" },

  // ---- Finance & back office ----
  { id:"brex", name:"Brex", category:"AI finance & spend",
    tags:["finance"],
    desc:"Corporate cards and spend management with AI controls.",
    sizes:["small","mid","large"], priceTier:"free", hasFreePlan:true, price:"Free (card-based)",
    ease:2, affiliate:"Referral / partner (verify)", commission:"Verify",
    url:"https://www.brex.com", site:"https://www.brex.com" },
  { id:"digits", name:"Digits", category:"AI accounting",
    tags:["finance"],
    desc:"AI-powered bookkeeping and financial reporting for SMBs.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:false, price:"Paid",
    ease:2, affiliate:"Verify availability", commission:"Verify",
    url:"https://digits.com", site:"https://digits.com" },

  // ---- IT & software development ----
  { id:"windsurf", name:"Windsurf", category:"Agentic AI IDE",
    tags:["itdev"],
    desc:"Agentic AI code editor (from Codeium) that builds and edits across files.",
    sizes:["small","mid","large"], priceTier:"low", hasFreePlan:true, price:"Free; from $15/mo",
    ease:2, affiliate:"None", commission:"—",
    url:"https://windsurf.com", site:"https://windsurf.com" },
  { id:"replit", name:"Replit", category:"AI app builder / IDE",
    tags:["itdev"],
    desc:"Build, host, and deploy apps in the browser with an AI agent.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:true, price:"Free; from $25/mo",
    ease:2, affiliate:"Verify availability", commission:"Verify",
    url:"https://replit.com", site:"https://replit.com" },
  { id:"lovable", name:"Lovable", category:"AI app builder",
    tags:["itdev"],
    desc:"Describe an app in plain English and Lovable builds the web app.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:true, price:"Free; from $25/mo",
    ease:1, affiliate:"Verify availability", commission:"Verify",
    url:"https://lovable.dev", site:"https://lovable.dev" },
  { id:"v0", name:"v0 by Vercel", category:"AI UI generation",
    tags:["itdev"],
    desc:"Generate React/UI components and pages from prompts.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; from $20/mo",
    ease:2, affiliate:"None", commission:"—",
    url:"https://v0.dev", site:"https://v0.dev" },

  // ---- Meetings & productivity ----
  { id:"zoomai", name:"Zoom AI Companion", category:"Meeting assistant",
    tags:["meetings"],
    desc:"Built-in AI summaries and recaps inside Zoom meetings.",
    sizes:["small","mid","large"], priceTier:"free", hasFreePlan:true, price:"Included with Zoom plans",
    ease:1, affiliate:"None", commission:"—",
    url:"https://www.zoom.com/en/ai-assistant", site:"https://www.zoom.com/en/ai-assistant" },
  { id:"tldv", name:"tl;dv", category:"AI meeting recorder",
    tags:["meetings","sales"],
    desc:"Records, transcribes, and summarizes meetings; syncs to your CRM.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; from $18/mo",
    ease:1, affiliate:"Has affiliate program (verify)", commission:"Verify",
    url:"https://tldv.io", site:"https://tldv.io" },
  { id:"readai", name:"Read.ai", category:"Meeting insights",
    tags:["meetings"],
    desc:"AI meeting summaries, transcripts, and engagement analytics.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; from $15/mo",
    ease:1, affiliate:"Verify availability", commission:"Verify",
    url:"https://www.read.ai", site:"https://www.read.ai" },
  { id:"reclaim", name:"Reclaim.ai", category:"AI scheduling",
    tags:["meetings"],
    desc:"Automatically schedules tasks, habits, and meetings on your calendar.",
    sizes:["small","mid"], priceTier:"low", hasFreePlan:true, price:"Free; from $8/mo",
    ease:1, affiliate:"Verify availability", commission:"Verify",
    url:"https://reclaim.ai", site:"https://reclaim.ai" },
  { id:"superhuman", name:"Superhuman", category:"AI email",
    tags:["meetings","sales"],
    desc:"Fast email client with AI triage, summaries, and writing.",
    sizes:["small","mid"], priceTier:"mid", hasFreePlan:false, price:"From $30/mo",
    ease:1, affiliate:"Verify availability", commission:"Verify",
    url:"https://superhuman.com", site:"https://superhuman.com" }
];

// Make available to the browser app AND to Node (for testing / xlsx export).
if (typeof module !== "undefined" && module.exports) { module.exports = AI_TOOLS; }
